# Generated by Django 4.2.27 on 2026-01-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('cooking_time', models.PositiveIntegerField(help_text='Time in minutes')),
                ('ingredients', models.ManyToManyField(related_name='recipes', to='ingredients.ingredient')),
            ],
        ),
    ]
